// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://inwsvuynfkxhswtzgggq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlud3N2dXluZmt4aHN3dHpnZ2dxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4OTg0NzQsImV4cCI6MjA3NDQ3NDQ3NH0.iU3W2u4dW0FM4XzPArH3tkFY6AfjwTzN7cIKFgz05tw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});